In [ ]:
#https://github.com/tvtaerum/xray_housekeeping/blob/master/files/images_convert_xrays.py

In [1]:
!pip install opendatasets


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [3]:
import opendatasets as od
import pandas
  
od.download("https://www.kaggle.com/datasets/paultimothymooney/chest-xray-pneumonia")

Please provide your Kaggle credentials to download this dataset. Learn more: http://bit.ly/kaggle-creds
Your Kaggle username: softwebdatascience
Your Kaggle Key: ··········


100%|██████████| 2.29G/2.29G [00:32<00:00, 75.0MB/s]


In [5]:
!rm -rf /content/xray/chest_xray/.DS_Store 

In [ ]:
#read and load data from folder

In [6]:
# example of extracting and resizing xrays into a new dataset
from os import listdir
from numpy import asarray
from numpy import savez_compressed
from PIL import Image
#from mtcnn.mtcnn import MTCNN
import pandas as pd
import numpy as np

np.set_printoptions(precision=3)
np.set_printoptions(suppress=True)
varNames = ["NORMAL","VIRAL","BACTERIAL"]

# load an image as an rgb numpy array
def load_image(filename):
    # load image from file
    image = Image.open(filename)
    # convert to RGB, if needed
    image = image.convert('RGB')
    # convert to array
    pixels = asarray(image)
    return pixels
 
# extract the xray from a loaded image and resize
def extract_xray(pixels, required_size=(80, 80)):
    # resize pixels to the model size
    image = Image.fromarray(pixels)
    image = image.resize(required_size)
    xray_array = asarray(image)
    return xray_array
 
# load images and extract xrays for all images in a directory
def load_xrays(directory, n_xrays):
    xrays = list()
    ids = list()
    labels = list()
    for dirname in listdir(directory):
        directory1=directory+dirname
        print("directory1: ", directory1)
        for dirname1 in listdir(directory1):
            directory2=directory1+"/"+dirname1
            print("directory2: ", directory2)
            # enumerate files
            for idx, filename in enumerate(listdir(directory2)):
                # load the image
                if "virus" in filename: label=1
                elif "bacteria" in filename: label=2
                else: label=0
                pixels = load_image(directory2 + "/" + filename)
                # print("pixels.size: ", pixels.size)
                # get xray
                xray = extract_xray(pixels)
                # print("pixels.size after extract: ", pixels.size)
                # if xray is None:
                    # continue
                # if data_attractive[idx] == -1.0:
                    # continue
                # store
                xrays.append(xray)
                ids.append(idx)
                labels.append(label)
                if (len(xrays)+1)%100==0:
                    print(len(xrays)+1, xray.shape)
                # stop once we have enough
                if len(xrays) >= n_xrays:
                    break
    return asarray(xrays),asarray(labels)
 
# directory that contains all images
directory = 'xray/chest_xray/'
# load and extract all xrays
n_xrays = 5200
# n_xrays = 100
all_xrays, all_labels = load_xrays(directory, n_xrays)
print('Loaded xrays: ', all_xrays.shape)
print('Loaded labels: ', all_labels.shape)
qSave = True
if qSave:
    savez_compressed('xray/img_align_xray.npz', all_xrays)
    savez_compressed('xray/labels_align_xray.npz', all_labels)

directory1:  xray/chest_xray/train
directory2:  xray/chest_xray/train/PNEUMONIA
100 (80, 80, 3)
200 (80, 80, 3)
300 (80, 80, 3)
400 (80, 80, 3)
500 (80, 80, 3)
600 (80, 80, 3)
700 (80, 80, 3)
800 (80, 80, 3)
900 (80, 80, 3)
1000 (80, 80, 3)
1100 (80, 80, 3)
1200 (80, 80, 3)
1300 (80, 80, 3)
1400 (80, 80, 3)
1500 (80, 80, 3)
1600 (80, 80, 3)
1700 (80, 80, 3)
1800 (80, 80, 3)
1900 (80, 80, 3)
2000 (80, 80, 3)
2100 (80, 80, 3)
2200 (80, 80, 3)
2300 (80, 80, 3)
2400 (80, 80, 3)
2500 (80, 80, 3)
2600 (80, 80, 3)
2700 (80, 80, 3)
2800 (80, 80, 3)
2900 (80, 80, 3)
3000 (80, 80, 3)
3100 (80, 80, 3)
3200 (80, 80, 3)
3300 (80, 80, 3)
3400 (80, 80, 3)
3500 (80, 80, 3)
3600 (80, 80, 3)
3700 (80, 80, 3)
3800 (80, 80, 3)
directory2:  xray/chest_xray/train/NORMAL
3900 (80, 80, 3)
4000 (80, 80, 3)
4100 (80, 80, 3)
4200 (80, 80, 3)
4300 (80, 80, 3)
4400 (80, 80, 3)
4500 (80, 80, 3)
4600 (80, 80, 3)
4700 (80, 80, 3)
4800 (80, 80, 3)
4900 (80, 80, 3)
5000 (80, 80, 3)
5100 (80, 80, 3)
5200 (80, 80, 3)
Loa

In [4]:
!ls -a /content/xray/chest_xray

.  ..  .DS_Store  train


In [ ]:
#testing after loading .npz file 

In [20]:
# example of a gan for generating faces
import numpy as np
import pandas as pd
from numpy import load
from numpy import zeros
from numpy import ones
from numpy import asarray
from numpy import append
from numpy.random import random
from numpy.random import randint
from numpy.random import shuffle
import time
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.optimizers import Adamax
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Reshape
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Conv2D
from tensorflow.keras.layers import Conv2DTranspose
from tensorflow.keras.layers import LeakyReLU
from tensorflow.keras.layers import Dropout
from tensorflow.keras.layers import Embedding
from tensorflow.keras.layers import Concatenate
import matplotlib.pyplot as plt
from tensorflow.keras.utils import plot_model
from matplotlib import patheffects as path_effects
import collections
from tensorflow.keras.models import load_model
from tensorflow import get_logger as log


def get_cumProbs(freqCategs, categs):
    freqLists = [freqCategs[i][1] for i in range(len(freqCategs))]
    freqListX = asarray(freqLists, dtype=np.float32)
    print("freqListX: ", freqListX)
    print("len(categs): ", len(categs))
    cumProbs = freqListX/len(categs)
    print("cumProbs: ", cumProbs)
    cumProbs = append((0.0),cumProbs)
    for i in range(len(cumProbs)-1):
        cumProbs[i+1]=cumProbs[i]+cumProbs[i+1]
    print("cumProbs: ", cumProbs)
    return cumProbs


 
# load and prepare training images
def load_real_samples():
    # load the face dataset
    data = load('xray/img_align_xray.npz')
    X = data['arr_0']
    # convert from unsigned ints to floats
    X = X.astype('float32')
    # scale from [0,255] to [-1,1]
    X = (X - 127.5) / 127.5
    data  = load('xray/labels_align_xray.npz')
    labels = data['arr_0']
    print("labels: ", labels)
    lenLabels = len(labels)
    print("lenLabels: ", lenLabels)
    lenrows = len(X)
    freqCategs = list(collections.Counter(sorted(labels)).items())
    print("freqCategs: ", freqCategs)
    cumProbs = get_cumProbs(freqCategs, labels)
    return [X, labels], cumProbs


# load image data
dataset, cumProbs = load_real_samples()




# select real samples
def generate_real_samples(dataset, n_samples):
    # print("n_samples: ", n_samples)
    # split into images and labels
    images, labels = dataset
    #print("images, labels:", images, labels)
    # choose random instances
    ix = randint(0, images.shape[0], n_samples)
    # print("ix: ", ix)
    # print("images.size: ", images.size)
    # print("labels.size: ", labels.size)
    # retrieve selected images
    X, labels = images[ix], labels[ix]
    print("X, labels", X, labels)
    # generate 'real' class labels (1)
    y = ones((n_samples, 1))
    return [X, labels], y



varNames = ["NORMAL","VIRAL","BACTERIAL"]
def save_real_plots(dataset, nRealPlots = 5, n=3, n_samples=100):
    # plot images
    for epoch in range(nRealPlots):
        if epoch%5==0:
            print("real_plots: ", epoch)
        # prepare real samples
        [X_real, labels], y_real = generate_real_samples(dataset, 100)
        fig, ax = plt.subplots(n, n, figsize=(15,15))
        ax=ax.flatten()
        # scale from [-1,1] to [0,1]
        X_real = (X_real + 1) / 2.0
        for i in range(n * n):
            # define subplot
            #fig = plt.subplot(n, n, 1 + i)
            strLabel = str(varNames[labels[i]])
            print("strLabel :", strLabel)
            # fig.title = strLabel
            # turn off axis
            #fig.axis('off')
            #fig.text(8.0,20.0,strLabel, fontsize=6, color='blue')
            ax[i].set_title(strLabel)
            # plot raw pixel data
            ax[i].imshow(X_real[i])
        # save plot to file
        filename = 'xray/test_/real_plot_e%03d.png' % (epoch+1)
        plt.savefig(filename)
        plt.close()
        
        
        
save_real_plots(dataset, nRealPlots=5)


labels:  [2 1 1 ... 0 0 0]
lenLabels:  5200
freqCategs:  [(0, 1325), (1, 1345), (2, 2530)]
freqListX:  [1325. 1345. 2530.]
len(categs):  5200
cumProbs:  [0.255 0.259 0.487]
cumProbs:  [0.    0.255 0.513 1.   ]
real_plots:  0
X, labels [[[[-1.    -1.    -1.   ]
   [-0.325 -0.325 -0.325]
   [ 0.004  0.004  0.004]
   ...
   [ 0.208  0.208  0.208]
   [ 0.129  0.129  0.129]
   [-0.192 -0.192 -0.192]]

  [[-1.    -1.    -1.   ]
   [-0.325 -0.325 -0.325]
   [ 0.035  0.035  0.035]
   ...
   [ 0.192  0.192  0.192]
   [ 0.114  0.114  0.114]
   [-0.184 -0.184 -0.184]]

  [[-1.    -1.    -1.   ]
   [-0.325 -0.325 -0.325]
   [ 0.051  0.051  0.051]
   ...
   [ 0.2    0.2    0.2  ]
   [ 0.129  0.129  0.129]
   [-0.192 -0.192 -0.192]]

  ...

  [[-0.741 -0.741 -0.741]
   [-0.49  -0.49  -0.49 ]
   [-0.278 -0.278 -0.278]
   ...
   [-0.89  -0.89  -0.89 ]
   [-0.953 -0.953 -0.953]
   [-1.    -1.    -1.   ]]

  [[-0.718 -0.718 -0.718]
   [-0.49  -0.49  -0.49 ]
   [-0.286 -0.286 -0.286]
   ...
   [-0.882 -0

In [14]:
!rm -rf /content/xray/test_

In [22]:
 pd.DataFrame(all_labels).value_counts()

2    2530
1    1345
0    1325
dtype: int64

In [ ]:
#train model

In [ ]:
# example of a gan for generating faces
import numpy as np
import pandas as pd
from numpy import load
from numpy import zeros
from numpy import ones
from numpy import asarray
from numpy import append
from numpy.random import random
from numpy.random import randint
from numpy.random import shuffle
import time
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.optimizers import Adamax
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Reshape
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Conv2D
from tensorflow.keras.layers import Conv2DTranspose
from tensorflow.keras.layers import LeakyReLU
from tensorflow.keras.layers import Dropout
from tensorflow.keras.layers import Embedding
from tensorflow.keras.layers import Concatenate
import matplotlib.pyplot as plt
from tensorflow.keras.utils import plot_model
from matplotlib import patheffects as path_effects
import collections
from tensorflow.keras.models import load_model
from tensorflow import get_logger as log

#  SET YOUR FLAGS
qErrorHide = False
if qErrorHide:
    print("\n***REMEMBER:  WARNINGS turned OFF***\n***REMEMBER:  WARNINGS turned OFF***\n")
    log().setLevel('ERROR')

#    INDICATE IF STARTING FRESH OR CONTINUING FROM PREVIOUS RUN
qRestart = False
if qRestart:
    epochs_done = 405
    epochs_goal = 410
else:
    epochs_done = 0
    epochs_goal = 100 

# define the standalone discriminator model
def define_discriminator(in_shape=(80,80,3), n_classes=3):
	print("**********  ENTERED discriminator  *****************")
	##### foundation for labels
	in_label = Input(shape=(1,))
	embedding_layer = Embedding(n_classes, 8)
	# embedding_layer.trainable = False
	li = embedding_layer (in_label)
	n_nodes = in_shape[0] * in_shape[1]
	print(">>embedding>> in_shape[0], in_shape[1], n_nodes: ", in_shape[0], in_shape[1], n_nodes)
	li = Dense(n_nodes)(li)
	li = Reshape((in_shape[0], in_shape[1], 1))(li)
	# image input
	dropout = 0.1
	in_image = Input(shape=in_shape)
	print("\nin_image: ", in_image)
	# concat label as a channel
	merge = Concatenate()([in_image, li])
	print("\nmerge.shape: ", merge.shape)
	# sample to 80x80
	fe = Conv2D(128, (5,5), padding='same')(merge)
	fe = LeakyReLU(alpha=0.2)(fe)
	fe = Dropout(dropout)(fe)
	print("fe.shape: ", fe.shape)
	# downsample to 40x40
	fe = Conv2D(128, (5,5), strides=(2,2), padding='same')(fe)
	fe = LeakyReLU(alpha=0.2)(fe)
	# fe = Dropout(dropout)(fe)
	print("fe.shape: ", fe.shape)
	# downsample to 20x20
	fe = Conv2D(128, (5,5), strides=(2,2), padding='same')(fe)
	fe = LeakyReLU(alpha=0.2)(fe)
	# fe = Dropout(dropout)(fe)
	print("fe.shape: ", fe.shape)
	# downsample to 10x10
	fe = Conv2D(128, (5,5), strides=(2,2), padding='same')(fe)
	fe = LeakyReLU(alpha=0.2)(fe)
	# fe = Dropout(dropout)(fe)
	print("fe.shape: ", fe.shape)
	# downsample to 5x5
	fe = Conv2D(128, (5,5), strides=(2,2), padding='same')(fe)
	fe = LeakyReLU(alpha=0.2)(fe)
	# fe = Dropout(dropout)(fe)
	print("fe.shape: ", fe.shape)
	# flatten feature maps
	fe = Flatten()(fe)
	# fe = Dropout(dropout)(fe)
	print("fe flatten shape: ", fe.shape)
	# output
	out_layer = Dense(1, activation='sigmoid')(fe)
	print("out_layer.shape: ", out_layer.shape)
	# define model
	model = Model([in_image, in_label], out_layer)
	print("\nmodel: ", model)
	# compile model
	# opt = Adamax(lr=0.00007, beta_1=0.08, beta_2=0.999, epsilon=10e-8)
	opt = Adamax(lr=0.00004, beta_1=0.08, beta_2=0.999, epsilon=10e-8)
	model.compile(loss='binary_crossentropy', optimizer=opt, metrics=['accuracy'])
	print("\nembedding_layer.get_weights(): \n",embedding_layer.get_weights())
	model.summary()
	plot_model(model, to_file='xray/discriminator_model.png')
	return model

# define the standalone generator model
def define_generator(latent_dim, n_classes=3):
	print("**********  ENTERED generator  *****************")
	##### foundation for labels
	in_label = Input(shape=(1,))
	embedding_layer = Embedding(n_classes, 8)
	embedding_layer.trainable = True
	li = embedding_layer (in_label)
	n_nodes = 5 * 5
	li = Dense(n_nodes)(li)
	li = Reshape((5 , 5, 1))(li)
	print("generator...  n_nodes, li.shape: ", n_nodes, li.shape)
	##### foundation for 5x5 image
	in_lat = Input(shape=(latent_dim,))
	n_nodes = 128 * 5 * 5
	genX = Dense(n_nodes)(in_lat)
	genX = LeakyReLU(alpha=0.2)(genX)
	genX = Reshape((5, 5, 128))(genX)
	dropout = 0.1
	print("genX.shape: ", genX.shape)
	##### merge image gen and label input
	merge = Concatenate()([genX, li])
	print("merge.shape: ", merge.shape)
	##### create merged model
	# upsample to 10x10
	gen = Conv2DTranspose(128, (4,4), strides=(2,2), padding='same')(merge)
	print("gen after CV2DT.shape: ", gen.shape)
	gen = LeakyReLU(alpha=0.2)(gen)
	gen = Dropout(dropout)(gen)
	print("gen.shape: ", gen.shape)
	# upsample to 20x20
	gen = Conv2DTranspose(128, (4,4), strides=(2,2), padding='same')(gen)
	gen = LeakyReLU(alpha=0.2)(gen)
	print("gen.shape: ", gen.shape)
	# upsample to 40x40
	gen = Conv2DTranspose(128, (4,4), strides=(2,2), padding='same')(gen)
	gen = LeakyReLU(alpha=0.2)(gen)
	print("gen.shape: ", gen.shape)
	# upsample to 80x80
	gen = Conv2DTranspose(128, (4,4), strides=(2,2), padding='same')(gen)
	gen = LeakyReLU(alpha=0.2)(gen)
	print("gen.shape: ", gen.shape)
	# output layer 80x80x3
	out_layer = Conv2D(3, (5,5), activation='tanh', padding='same')(gen)
	print("out_layer.shape: ", out_layer.shape)
	# define model
	model = Model(inputs=[in_lat, in_label], outputs=out_layer)
	opt = Adamax(lr=0.0002, beta_1=0.5, beta_2=0.999, epsilon=10e-8)
	model.compile(loss=['binary_crossentropy'], optimizer=opt)
	print("\nembedding_layer.get_weights(): \n",embedding_layer.get_weights())
	model.summary()
	plot_model(model, to_file='xray/generator_model.png')
	return model
 
# define the combined generator and discriminator model, for updating the generator
def define_gan(g_model, d_model):
	print("**********  ENTERED gan  *****************")
	# make weights in the discriminator not trainable
	d_model.trainable = False
	# get noise and label inputs from generator model
	gen_noise, gen_label = g_model.input
	# get image output from the generator model
	gen_output = g_model.output
	# connect image output and label input from generator as inputs to discriminator
	gan_output = d_model([gen_output, gen_label])
	# define gan model as taking noise and label and outputting a classification
	model = Model([gen_noise, gen_label], gan_output)
	# compile model
	opt = Adamax(lr=0.0002, beta_1=0.5, beta_2=0.999, epsilon=10e-8)
	model.compile(loss='binary_crossentropy', optimizer=opt)
	model.summary()
	plot_model(model, to_file='xray/gan_model.png')
	return model

# assign categories
def assign_categs(df, lenrows):
	print("\n*****  ATTRIBUTES: \n", df.mean())
	return categs

def get_cumProbs(freqCategs, categs):
	freqLists = [freqCategs[i][1] for i in range(len(freqCategs))]
	freqListX = asarray(freqLists, dtype=np.float32)
	print("freqListX: ", freqListX)
	print("len(categs): ", len(categs))
	cumProbs = freqListX/len(categs)
	print("cumProbs: ", cumProbs)
	cumProbs = append((0.0),cumProbs)
	for i in range(len(cumProbs)-1):
		cumProbs[i+1]=cumProbs[i]+cumProbs[i+1]
	print("cumProbs: ", cumProbs)
	return cumProbs


 
# load and prepare training images
def load_real_samples():
	# load the face dataset
	data = load('xray/img_align_xray.npz')
	X = data['arr_0']
	# convert from unsigned ints to floats
	X = X.astype('float32')
	# scale from [0,255] to [-1,1]
	X = (X - 127.5) / 127.5
	data  = load('xray/labels_align_xray.npz')
	labels = data['arr_0']
	print("labels: ", labels)
	lenLabels = len(labels)
	print("lenLabels: ", lenLabels)
	lenrows = len(X)
	freqCategs = list(collections.Counter(sorted(labels)).items())
	print("freqCategs: ", freqCategs)
	cumProbs = get_cumProbs(freqCategs, labels)
	return [X, labels], cumProbs
 
# select real samples
def generate_real_samples(dataset, n_samples):
	# print("n_samples: ", n_samples)
	# split into images and labels
	images, labels = dataset
	# choose random instances
	ix = randint(0, images.shape[0], n_samples)
	# print("ix: ", ix)
	# print("images.size: ", images.size)
	# print("labels.size: ", labels.size)
	# retrieve selected images
	X, labels = images[ix], labels[ix]
	# generate 'real' class labels (1)
	y = ones((n_samples, 1))
	return [X, labels], y
 
# generate points in latent space as input for the generator
def generate_latent_points(latent_dim, n_samples, cumProbs, n_classes=3):
	# print("generate_latent_points: ", latent_dim, n_samples)
	initX = -3.0
	rangeX = 2.0*abs(initX)
	stepX = rangeX / (latent_dim * n_samples)
	x_input = asarray([initX + stepX*(float(i)) for i in range(0,latent_dim * n_samples)])
	shuffle(x_input)
	# generate points in the latent space
	z_input = x_input.reshape(n_samples, latent_dim)
	randx = random(n_samples)
	labels = np.zeros(n_samples, dtype=int)
	for i in range(n_classes):
		labels = np.where((randx >= cumProbs[i]) & (randx < cumProbs[i+1]), i, labels)
	return [z_input, labels]
 
# use the generator to generate n fake examples, with class labels
def generate_fake_samples(generator, latent_dim, n_samples, cumProbs):
	# generate points in latent space
	z_input, labels_input = generate_latent_points(latent_dim, n_samples, cumProbs)
	# predict outputs
	images = generator.predict([z_input, labels_input])
	# create class labels
	y = zeros((n_samples, 1))
	return [images, labels_input], y
 
# create and save a plot of generated images
def save_plot(examples, labels, epoch, n=10):
	# scale from [-1,1] to [0,1]
	examples = (examples + 1) / 2.0
	# plot images
	for i in range(n * n):
		# define subplot
		fig = plt.subplot(n, n, 1 + i)
		strLabel = str(labels[i])
		# turn off axis
		fig.axis('off')
		fig.text(8.0,20.0,strLabel, fontsize=6, color='white')
		# plot raw pixel data
		fig.imshow(examples[i])
	# save plot to file
	filename = 'xray/results/generated_plot_e%03d.png' % (epoch+1)
	plt.savefig(filename)
	plt.close()
	
def save_real_plots(dataset, nRealPlots = 5, n=10, n_samples=100):
	# plot images
	for epoch in range(nRealPlots):
		if epoch%5==0:
			print("real_plots: ", epoch)
		# prepare real samples
		[X_real, labels], y_real = generate_real_samples(dataset, n_samples)
		# scale from [-1,1] to [0,1]
		X_real = (X_real + 1) / 2.0
		for i in range(n * n):
			# define subplot
			fig = plt.subplot(n, n, 1 + i)
			strLabel = str(labels[i])
			# fig.title = strLabel
			# turn off axis
			fig.axis('off')
			fig.text(8.0,20.0,strLabel, fontsize=6, color='white')
			# plot raw pixel data
			fig.imshow(X_real[i])
		# save plot to file
		filename = 'xray/real_plots/real_plot_e%03d.png' % (epoch+1)
		plt.savefig(filename)
		plt.close()
 
# evaluate the discriminator, plot generated images, save generator model
def summarize_performance(epoch, g_model, d_model, gan_model, dataset, latent_dim, n_samples=100):
    # prepare real samples
    [X_real, labels_real], y_real = generate_real_samples(dataset, n_samples)
    # evaluate discriminator on real examples
    _, acc_real = d_model.evaluate([X_real, labels_real], y_real, verbose=0)
    # prepare fake examples
    [X_fake, labels], y_fake = generate_fake_samples(g_model, latent_dim, n_samples, cumProbs)
    # evaluate discriminator on fake examples
    _, acc_fake = d_model.evaluate([X_fake, labels], y_fake, verbose=0)
    # summarize discriminator performance
    print('>Accuracy real: %.0f%%, fake: %.0f%%' % (acc_real*100, acc_fake*100))
    # save plot
    save_plot(X_fake, labels, epoch)
    # save the generator model tile file
    filename = 'xray/results/generator_model_%03d.h5' % (epoch+1)
    g_model.save(filename)
    #save on drive
    filename_generate = '/content/drive/MyDrive/cGAN_xray/xray/results/generator_model_%03d.h5' % (epoch+1)
    g_model.save(filename_generate)
 
    filename = 'xray/results/generator_model_gan%03d.h5' % (epoch+1)
    gan_model.save(filename)
 
    #save on drive
    filename_gan = '/content/drive/MyDrive/cGAN_xray/xray/results/generator_model_gan%03d.h5' % (epoch+1)
    gan_model.save(filename_gan)
 
    filename = 'xray/results/generator_model_dis%03d.h5' % (epoch+1)
    filename_dis = '/content/drive/MyDrive/cGAN_xray/xray/results/generator_model_dis%03d.h5' % (epoch+1)

    d_model.trainable = True
    for layer in d_model.layers:
        layer.trainable = True
    d_model.save(filename)
    d_model.save(filename_dis)
    d_model.trainable = False
    for layer in d_model.layers:
        layer.trainable = False


def restart(epochs_done):
	# gen_weights = array(model.get_weights())
	print("****  restart PULLING IN EPOCH: ", epochs_done)
	filename = 'xray/results/generator_model_dis%03d.h5' % (epochs_done)
	d_model = load_model(filename, compile=True)
	d_model.trainable = True
	for layer in d_model.layers:
		layer.trainable = True
	d_model.summary()
	filename = 'xray/results/generator_model_%03d.h5' % (epochs_done)
	g_model = load_model(filename, compile=True)
	g_model.summary()
	gan_model = define_gan(g_model, d_model)
	gan_model.summary()
	return d_model, g_model, gan_model

 
# train the generator and discriminator
def train(g_model, d_model, gan_model, dataset, latent_dim, epochs_goal=100, n_batch=128, epochs_done=0):
	nTryAgains = 0
	nTripsOnSameSavedWts = 0
	nSaves = 0
	bat_per_epo = int(dataset[0].shape[0] / n_batch)
	half_batch = int(n_batch / 2)
	d_trainable_weights = np.array(d_model.get_weights())
	g_trainable_weights = np.array(g_model.get_weights())
	gan_trainable_weights = np.array(gan_model.get_weights())
	now = time.time()
	ij = 0
	ijSave = -100
	# manually enumerate epochs
	for i in range(epochs_done, epochs_goal):
		# enumerate batches over the training set
		for j in range(bat_per_epo):
			ij+=1
			# get randomly selected 'real' samples
			[X_real, labels_real], y_real = generate_real_samples(dataset, half_batch)
			qDebug=False
			# update discriminator model weights
			dis_loss, _ = d_model.train_on_batch([X_real, labels_real], y_real)
			[X_fake, labels], y_fake = generate_fake_samples(g_model, latent_dim, half_batch, cumProbs)
			gen_loss, _ = d_model.train_on_batch([X_fake, labels], y_fake)
			[z_input, labels_input] = generate_latent_points(latent_dim, n_batch, cumProbs)
			# create inverted labels for the fake samples
			y_gan = ones((n_batch, 1))
			# update the generator via the discriminator's error
			gan_loss = gan_model.train_on_batch([z_input, labels_input], y_gan)
			# summarize loss on this batch
			if (j+1) % 5==0 or dis_loss > 1.10 or gen_loss > 1.10 or gan_loss > 1.80:
				diff = int(time.time()-now)
				print('>%d/%d, %d/%d, d1=%.3f, d2=%.3f, g=%.3f, secs=%d, tryAgain=%d, nTripsOnSameSavedWts=%d, nSaves=%d' %
					(i+1, epochs_goal, j+1, bat_per_epo, dis_loss, gen_loss, gan_loss, diff, nTryAgains, nTripsOnSameSavedWts, nSaves))
			if dis_loss > 0.30 and dis_loss < 0.95 and gen_loss > 0.25 and gen_loss < 0.95 and gan_loss > 0.40 and gan_loss < 1.50:
				nTripsOnSameSavedWts = 0
				if ij - ijSave > 8:
					nSaves+=1
					ijSave = ij
					d_trainable_weights = np.array(d_model.get_weights())
					g_trainable_weights = np.array(g_model.get_weights())
					gan_trainable_weights = np.array(gan_model.get_weights())
			if (dis_loss < 0.001 or dis_loss > 2.0) and ijSave > 0:
				nTryAgains+=1
				nTripsOnSameSavedWts+=1
				print("LOADING d_model",j+1," from ",ijSave)
				d_model.set_weights(d_trainable_weights)
			if (gen_loss < 0.001 or gen_loss > 2.0) and ijSave > 0:
				nTryAgains+=1
				nTripsOnSameSavedWts+=1
				print("LOADING g_model",j+1," from ",ijSave)
				g_model.set_weights(g_trainable_weights)
			if (gan_loss < 0.010 or gan_loss > 3.00) and ijSave > 0:
				nTryAgains+=1
				nTripsOnSameSavedWts+=1
				print("LOADING gan_models",j+1," from ",ijSave)
				gan_model.set_weights(gan_trainable_weights)
			# if (j+1) % 10 == 0:
				# summarize_performance(i, g_model, d_model, dataset, latent_dim)
			if nTripsOnSameSavedWts > 20:
				print("**********  Too many rebuilds  **************")
				summarize_performance(i, g_model, d_model, dataset, latent_dim)
				import sys
				sys.exit(0)
		# evaluate the model performance, sometimes
		if (i+1) % 10 == 0:
			summarize_performance(i, g_model, d_model, gan_model, dataset, latent_dim)

# size of the latent space
latent_dim = 100

if qRestart:
        d_model, g_model, gan_model = restart(epochs_done = epochs_done)
else:
        # create the discriminator
        d_model = define_discriminator()
        # create the generator
        g_model = define_generator(latent_dim)
        # create the gan
        gan_model = define_gan(g_model, d_model)
        
# load image data
dataset, cumProbs = load_real_samples()
save_real_plots(dataset, nRealPlots=2)
train(g_model, d_model, gan_model,  dataset, latent_dim, epochs_goal=epochs_goal, n_batch=64, epochs_done=epochs_done)

**********  ENTERED discriminator  *****************
>>embedding>> in_shape[0], in_shape[1], n_nodes:  80 80 6400

in_image:  KerasTensor(type_spec=TensorSpec(shape=(None, 80, 80, 3), dtype=tf.float32, name='input_2'), name='input_2', description="created by layer 'input_2'")

merge.shape:  (None, 80, 80, 4)
fe.shape:  (None, 80, 80, 128)
fe.shape:  (None, 40, 40, 128)
fe.shape:  (None, 20, 20, 128)
fe.shape:  (None, 10, 10, 128)
fe.shape:  (None, 5, 5, 128)
fe flatten shape:  (None, 3200)
out_layer.shape:  (None, 1)

model:  <keras.engine.functional.Functional object at 0x7f0dba603790>

embedding_layer.get_weights(): 
 [array([[-0.03073829, -0.01215079, -0.00531125, -0.02493281,  0.01293297,
         0.04408422, -0.04566335, -0.04072207],
       [ 0.00952963, -0.02093607,  0.04980237, -0.02807131,  0.03324424,
        -0.02106849, -0.01918643, -0.04431773],
       [ 0.02181245,  0.01519055,  0.01509266,  0.00776792, -0.02830525,
         0.04420697, -0.02943773,  0.01485443]], dtype=f

/usr/local/lib/python3.7/dist-packages/keras/optimizer_v2/adamax.py:90: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(Adamax, self).__init__(name, **kwargs)


**********  ENTERED generator  *****************
generator...  n_nodes, li.shape:  25 (None, 5, 5, 1)
genX.shape:  (None, 5, 5, 128)
merge.shape:  (None, 5, 5, 129)
gen after CV2DT.shape:  (None, 10, 10, 128)
gen.shape:  (None, 10, 10, 128)
gen.shape:  (None, 20, 20, 128)
gen.shape:  (None, 40, 40, 128)
gen.shape:  (None, 80, 80, 128)
out_layer.shape:  (None, 80, 80, 3)

embedding_layer.get_weights(): 
 [array([[ 0.02609141,  0.04059908,  0.03537095, -0.03931664,  0.00807967,
         0.00598494, -0.01399331, -0.02770642],
       [ 0.04869303, -0.03044518,  0.01213712,  0.00357984,  0.04108752,
         0.03712373,  0.03362192, -0.03308418],
       [ 0.03968811,  0.00387245,  0.01346829,  0.04375852,  0.0277721 ,
        -0.04825039,  0.03543046,  0.03246847]], dtype=float32)]
Model: "model_1"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                   

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:377: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:378: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:379: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
/usr

>1/100, 5/81, d1=0.578, d2=0.699, g=0.688, secs=9, tryAgain=0, nTripsOnSameSavedWts=0, nSaves=1
>1/100, 10/81, d1=0.391, d2=0.745, g=0.652, secs=11, tryAgain=0, nTripsOnSameSavedWts=0, nSaves=1
>1/100, 15/81, d1=0.206, d2=0.815, g=0.645, secs=13, tryAgain=0, nTripsOnSameSavedWts=0, nSaves=2
>1/100, 20/81, d1=0.108, d2=0.560, g=0.909, secs=15, tryAgain=0, nTripsOnSameSavedWts=0, nSaves=2
>1/100, 25/81, d1=0.045, d2=0.628, g=0.771, secs=17, tryAgain=0, nTripsOnSameSavedWts=0, nSaves=2
>1/100, 30/81, d1=0.026, d2=0.689, g=0.702, secs=19, tryAgain=0, nTripsOnSameSavedWts=0, nSaves=2
>1/100, 35/81, d1=0.061, d2=1.033, g=0.478, secs=21, tryAgain=0, nTripsOnSameSavedWts=0, nSaves=2
>1/100, 36/81, d1=0.055, d2=1.128, g=0.436, secs=21, tryAgain=0, nTripsOnSameSavedWts=0, nSaves=2
>1/100, 37/81, d1=0.075, d2=1.230, g=0.404, secs=22, tryAgain=0, nTripsOnSameSavedWts=0, nSaves=2
>1/100, 38/81, d1=0.066, d2=1.328, g=0.379, secs=22, tryAgain=0, nTripsOnSameSavedWts=0, nSaves=2
>1/100, 39/81, d1=0.07

In [1]:
!cp -r /content/xray_ /content/drive/MyDrive/cGAN_xray

In [2]:
!rm -rf /content/drive/MyDrive/cGAN_xray/xray/real_plots

In [ ]:
#inferernce model----------------

In [9]:
# example of a gan for generating faces
import numpy as np
import pandas as pd
from numpy import load
from numpy import zeros
from numpy import ones
from numpy import asarray
from numpy import append
from numpy.random import random
from numpy.random import randint
from numpy.random import shuffle
import time
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.optimizers import Adamax
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Reshape
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Conv2D
from tensorflow.keras.layers import Conv2DTranspose
from tensorflow.keras.layers import LeakyReLU
from tensorflow.keras.layers import Dropout
from tensorflow.keras.layers import Embedding
from tensorflow.keras.layers import Concatenate
import matplotlib.pyplot as plt
from tensorflow.keras.utils import plot_model
from matplotlib import patheffects as path_effects
import collections
from tensorflow.keras.models import load_model
from tensorflow import get_logger as log


# generate points in latent space as input for the generator
def generate_latent_points(latent_dim, n_samples, cumProbs, n_classes=3):
	# print("generate_latent_points: ", latent_dim, n_samples)
	initX = -3.0
	rangeX = 2.0*abs(initX)
	stepX = rangeX / (latent_dim * n_samples)
	x_input = asarray([initX + stepX*(float(i)) for i in range(0,latent_dim * n_samples)])
	shuffle(x_input)
	# generate points in the latent space
	z_input = x_input.reshape(n_samples, latent_dim)
	randx = random(n_samples)
	labels = np.zeros(n_samples, dtype=int)
	for i in range(n_classes):
		labels = np.where((randx >= cumProbs[i]) & (randx < cumProbs[i+1]), i, labels)
	return [z_input, labels]
 
# use the generator to generate n fake examples, with class labels
def generate_fake_samples(generator, latent_dim, n_samples, cumProbs):
	# generate points in latent space
	z_input, labels_input = generate_latent_points(latent_dim, n_samples, cumProbs)
	# predict outputs
	images = generator.predict([z_input, labels_input])
	# create class labels
	y = zeros((n_samples, 1))
	return [images, labels_input], y
 
"""
# create and save a plot of generated images
def save_plot(examples, labels, epoch, n=10):
	# scale from [-1,1] to [0,1]
	examples = (examples + 1) / 2.0
	# plot images
	for i in range(n * n):
		# define subplot
		fig = plt.subplot(n, n, 1 + i)
		strLabel = str(labels[i])
		# turn off axis
		fig.axis('off')
		fig.text(8.0,20.0,strLabel, fontsize=6, color='white')
		# plot raw pixel data
		fig.imshow(examples[i])
	# save plot to file
	filename = './generated_plot_e%03d.png' % (epoch+1)
	plt.savefig(filename)
	plt.close()
 
 """
# create and save a plot of generated images
def save_plot(examples, labels, epoch, n=3):
    
    varNames = ["NORMAL","VIRAL","BACTERIAL"]

    # scale from [-1,1] to [0,1]
    fig, ax = plt.subplots(n, n, figsize=(15,15))
    examples = (examples + 1) / 2.0
    ax=ax.flatten()
    # plot images
    for i in range(n * n):
        # define subplot
        #fig = plt.subplot(n, n, 1 + i)
        strLabel = str(varNames[labels[i]])
        # turn off axis
        #fig.axis('off')
        #fig.text(8.0,20.0,strLabel, fontsize=6, color='white')
        # plot raw pixel data
        #fig.imshow(examples[i])
        ax[i].set_title(strLabel)
        # plot raw pixel data
        ax[i].imshow(examples[i])
    # save plot to file
    filename = './generated_plot_e%03d.png' % (epoch+1)
    plt.savefig(filename)
    plt.close()
 

 
# evaluate the discriminator, plot generated images, save generator model
def summarize_performance(epoch, g_model, d_model, latent_dim,cumProbs, n_samples=100):
	# prepare fake examples
	[X_fake, labels], y_fake = generate_fake_samples(g_model, latent_dim, n_samples, cumProbs)
	# evaluate discriminator on fake examples
	_, acc_fake = d_model.evaluate([X_fake, labels], y_fake, verbose=0)
	# summarize discriminator performance
	#print('>Accuracy real: %.0f%%, fake: %.0f%%' % (acc_real*100, acc_fake*100))
	# save plot
	save_plot(X_fake, labels, epoch)
 


g =load_model("/content/drive/MyDrive/cGAN_xray/xray/results/generator_model_040.h5")
d =load_model("/content/drive/MyDrive/cGAN_xray/xray/results/generator_model_dis040.h5")
latent_dim = 100
cumProbs = [0.,         0.2696918,  0.52534249, 1.00000003]
summarize_performance(111, g, d,latent_dim, cumProbs, n_samples=100)

In [ ]:

varNames = ["NORMAL","VIRAL","BACTERIAL"]
def save_real_plots(dataset, nRealPlots = 5, n=3, n_samples=100):
    # plot images
    for epoch in range(nRealPlots):
        if epoch%5==0:
            print("real_plots: ", epoch)
        # prepare real samples
        [X_real, labels], y_real = generate_real_samples(dataset, 100)
        fig, ax = plt.subplots(n, n, figsize=(15,15))
        ax=ax.flatten()
        # scale from [-1,1] to [0,1]
        X_real = (X_real + 1) / 2.0
        for i in range(n * n):
            # define subplot
            #fig = plt.subplot(n, n, 1 + i)
            strLabel = str(varNames[labels[i]])
            print("strLabel :", strLabel)
            # fig.title = strLabel
            # turn off axis
            #fig.axis('off')
            #fig.text(8.0,20.0,strLabel, fontsize=6, color='blue')
            ax[i].set_title(strLabel)
            # plot raw pixel data
            ax[i].imshow(X_real[i])
        # save plot to file
        filename = 'xray/test_/real_plot_e%03d.png' % (epoch+1)
        plt.savefig(filename)
        plt.close()
        